"""New columns in metrics model

Revision ID: 46dbfbf2eb33
Revises: f7ad4ba8e1b5
Create Date: 2026-07-25 07:14:29.152027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46dbfbf2eb33'
down_revision: Union[str, Sequence[str], None] = 'f7ad4ba8e1b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('metrics', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('metrics', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'synced_at')
    op.drop_column('metrics', 'last_attempt_at')
    op.drop_column('metrics', 'attempts')
    # ### end Alembic commands ###
